# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
  # Make controller services available for autowiring with constructor arguments
  App\Controller\:
    resource: '../src/Controller/'
    tags: ['controller.service_arguments']
